### ISSUE TITLE
Cider 2 from Microsoft Store - never properly signing in and always building playlist cache

### ISSUE THREAD

**Issue by celsiusqc** [ciderapp/Cider-2#239]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

6/6/2023

### Operating System Version

Windows 11 Insider Preview 10.0.22631.1825

### Describe the Bug

![image](https://github.com/ciderapp/Cider-2/assets/63996164/5aafa5ae-f4eb-4c8e-a67e-e19c20350cf4)
As you can see in the picture, it endlessly tries to build cache and never properly logs in.

### Steps to Reproduce

Download the program and log in?

**Comment by celsiusqc** [comment]
Also, when I close the program, I have to sign in again everytime

**Comment by alexvojacek** [comment]
Similar thing is happening with me.  Building cache stuck, but I only get 64kbit low quality on most tracks, which makes the whole point of using this program moot.

**Comment by jaydeelive01** [comment]
I also have this issue.

**Comment by coredev-uk** [comment]
The playlist build cache notification is erroring because you have no playlists. As for the login issue, I don't think this is something I can reproduce. I suggest uninstalling the app or resetting it through the Windows settings.

@alexvojacek As for your issue, we already discussed our reasoning with it, and for any other user visiting this thread refer to #206
