### ISSUE TITLE
[Bug]: Failed to Authorize Apple Music

### ISSUE THREAD

**Issue by ArgonGaming** [ciderapp/Cider-2#279]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Latest

### Operating System Version

Windows 11

### Describe the Bug

Everytime I try to sign in to Apple Music it pops up with an error namely "Failed to Authorize Apple Music". Otherwise the majority of the UI is blank and does not have any songs or lists showing

### Steps to Reproduce

1) Installed Cider on Windows 11
2) Try to sign into Apple Music

### Build timestamp

1688278531297

**Comment by AyoungDukie** [comment]
This is occurring for me on Windows 10 as well, via the Microsoft Store variant. It seems related to #170 as the console shows an error about it (however, the workaround does not seem to work on the latest builds):
![image](https://github.com/ciderapp/Cider-2/assets/5449443/ea6c8004-3916-4018-991b-656c2f2b2c84)
![image](https://github.com/ciderapp/Cider-2/assets/5449443/2191402d-460f-42f0-979a-3e27503fca80)

However, it seems partially affected by something with Edge itself. I noticed that just leaving the window fragment trying to load in the background would eventually show a timeout. I then tried copying the authentication URL directly to a full Edge window. This ***also*** timed out, but navigating to https://music.apple.com would load fine. 

I logged in there, tried re-loading the token authentication URL, and suddenly the page loaded both in the full edge window and in the fragment Cider window. That said, signing-in ends with an "There was an Issue Connecting" page with a few 401 errors and an issue about storefront codes?
![image](https://github.com/ciderapp/Cider-2/assets/5449443/fef5d50b-60d5-431d-8e58-853cccfaee3c)
![image](https://github.com/ciderapp/Cider-2/assets/5449443/3bc3f5cf-cdfd-496d-a719-65d7fc874238)

Cider will then act as though it is connected and start loading songs, but only partially gets into the library before becoming stuck. The console then shows the previous LocalStorage error.

I have since also tried resetting the app via Settings, and completely reinstalling, but no success.

I also tried closing edge completely on one of the reset attempts, and again began having the early issue where it would fail to connect.

**Comment by cryptofyre** [comment]
Fixed in 2.2.0
