### ISSUE TITLE
Playlist Cache not working/Not showing any playlists

### ISSUE THREAD

**Issue by thecute** [ciderapp/Cider-2#284]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Built on 2023-05-17, 1:25:48 a.m. | Quasar v2.11.10 | Sabiiro

### Operating System Version

Edition: Windows 11 Pro Version 22H2 | Installed on: 2023-‎02-‎10 | OS build: 22621.1848 | Experience: Windows Feature Experience Pack 1000.22642.1000.0

### Describe the Bug

Playlist cache won't build and as a result my playlists don't show in Cider. I've tried to load Cider with the Client DB enabled and disabled but it doesn't seem to be responsible as I get the same result regardless. 

![Screenshot 2023-07-06 134124](https://github.com/ciderapp/Cider-2/assets/20833924/1a3b62ac-e706-43e0-880b-f2f25406b1a9)

### Steps to Reproduce

Open Cider. 

### Anything else?

![image](https://github.com/ciderapp/Cider-2/assets/20833924/29e33804-4c0f-4f9f-bb47-a00b474fb61c)

**Comment by marie0llie** [comment]
I would also like to add to this: Logging out and logging back in brings up an error from Apple Music.
![image](https://github.com/ciderapp/Cider-2/assets/43187285/34f001ed-ae3d-47b8-aaa5-b260ac7e0c00)
Afterwards, it seems like you are logged in, but actions relating to your account do not work. Adding songs to playlists or looking at playlists acts like you are using a completely different account with certain buttons used to add the playlist to your library showing up.
![image](https://github.com/ciderapp/Cider-2/assets/43187285/4b81d83f-0afc-4693-9f96-85fe23f3a4ba)
This happened after I was offline for a bit. Once I connected back to my network, this occurred. You can still listen to music but many features are broken because of this.

**Comment by marie0llie** [comment]
NOTE: Mentioned in #283

**Comment by Shotz5** [comment]
+1 this issue. Not sure I changed anything recently that would have caused this issue to spring up.

**Comment by Vinicius-Icaro** [comment]
Same problem here

**Comment by marclallen** [comment]
I'm also seeing this problem. I upgraded my system a couple of weeks ago. I also got the network connection error, but it eventually gave me playlists and such. I was using it fine. Today, after not using it for a week or more, it no longer loads any music and I still get the strange login issue.

**Comment by jvdutrag** [comment]
+1

**Comment by cryptofyre** [comment]
Fixed in v2.1, closing this issue for the time being.

**Comment by Felipe-9** [comment]
This problem came back on 2.6.2
