### ISSUE TITLE
Login process does not complete

### ISSUE THREAD

**Issue by eatmyvenom** [ciderapp/Cider-2#366]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Linux

### Build Details

2.2.0.r3799.df6bae16-1

### Operating System Version

Arch Linux Linux venom-pc 6.5.3-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Wed, 13 Sep 2023 08:37:16 +0000 x86_64 GNU/Linux

### Describe the Bug

Logging in does nothing, when the process is complete it will just open apple music in the little login window.

### Steps to Reproduce

Same issue:
1. Open Cider 2
2. Click "Login to Apple Music"
3. Enter login info
4. Login window just opens apple music.

### Anything else?

My environment is gnome on wayland. I use gnome keyring and everything. I don't have a special electron installed or being used.

**Comment by eatmyvenom** [comment]
I forgot to mention, the solution mentioned in #170 doesn't appear to work here. Killing the process and uninstalling then reinstalling does nothing, and Ctrl+Shift+I does not open developer tools so that doesn't help either.

**Comment by Consuderably** [comment]
exact same issue on Arch (hyprland and X11 on bspwm) and with macOS on m2 air, both stayed signed in from previous installations but will not register new users.

**Comment by cryptofyre** [comment]
Known issue, we're tracking this right now and working on a fix. We'll let you know once we have a solution.

**Comment by cryptofyre** [comment]
Currently you can work around this by opening a web browser and signing into Apple Music on the Web and copying your token.


1. Go to [AM Web](https://beta.music.apple.com)

2. Login and then press Shift + Ctrl + I (Open Developer Tools)

3. Head over to the "Storage"/"Application" section.

4. Navigate to Cookies and then https://beta.music.apple.com and or https://music.apple.com

5. Click on Filter Items or Press Ctrl + F and search `media-user-token`

6. Double click it and copy your token.

7. Then proceed to sign in using your token instead of using the normal OAuth process.

**Comment by MikhailTNY** [comment]
Thanks, that works.

**Comment by cryptofyre** [comment]
Fixed in 2.2.0-RV2 you can download it from Itch.io.
