### ISSUE TITLE
[Bug]: Discord RPC stops working if you change Client Name

### ISSUE THREAD

**Issue by IsaacMarovitz** [ciderapp/Cider-2#441]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

macOS

### Build Details

Version 2.2.0 (Built 21/09/2023)

### Operating System Version

macOS Sonoma 14.1

### Describe the Bug

If you change the Client Name in Cider settings, Discord RPC will stop working till you next relaunch Cider.

### Steps to Reproduce

1. Change Client Name (e.g. `Cider` -> `Cider 2`)
2. Discord RPC stops displaying
3. Relaunch Cider
4. Discord RPC works again with new name

**Comment by coredev-uk** [comment]
This is probably the case of an RPC connection timeout. DiscordRPC is a bit funky sometimes and prevents 2 client IDs from the same application. I recommend a restart after changing the client ID. Not much more can be done on our end, this is how Discord does it and changing the client ID is not standard expected behaviour from an application.
