### ISSUE TITLE
[Bug]:Podcast episode no sound on first try

### ISSUE THREAD

**Issue by huntdogy** [ciderapp/Cider-2#550]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that I am using a supported version of Cider. You can find the list of supported versions [here](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md).
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).

### What operating system are you using?

Windows

### Build Details

2.3.2-prerelease9 | Built on 2/23/2024, 4:16:32 AM | Sabiiro | d1c261e94c396f849fc875d6b2aa0a07ab9d31b2

### Operating System Version

Windows 10 Pro Version 22H2 19045.4046

### Describe the Bug

Try to play a podcast and it will remain silent until you click on another podcast and then click back on the podcast episode you want to play.

### Steps to Reproduce

1. Open podcasts
2. select podcast episode you want to listen to
3. select different episode and try other one

### Build timestamp

1708735011806

**Comment by jamesdesilva14** [comment]
I have experienced this bug with the linux version as well.
System info:
OS: popOS 22.04 LTS
Cider version: 2.3.1 (latest from itch.io)
Built on 2/7/2024, 10:25:22 PM

Additional Notes:
This only happens when a podcast is the first thing played upon opening the app.  If music is played first and then you try to play a podcast, the podcast will play first try.  If the first thing you try to play is a podcast, it will look like it is playing (timestamp increments, length displayed correctly), but no sound will be output.

**Comment by NintyS** [comment]
I have it too. Latest Nobara with latest Cider.
