### ISSUE TITLE
Playback stopping on some songs and messes up queue on resume

### ISSUE THREAD

**Issue by quiellll** [ciderapp/Cider-2#631]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Arch Linux

### Build Timestamp

05/07/2024 @ 04:22:08 AM

### Describe the Bug

Songs stop playing after a short period of time, approximately around the 1:00-2:00 mark in my case. 
Hitting play restarts the song, and instead of continuing with the desired queue, it uses the history as a queue.

In my case, it used my history (with songs that I had played earlier on my phone) and used it as a queue instead of the rest of the songs of the album.

Also, if a song has gotten stuck, it will get stuck more times. The only way that I've found to avoid this issue is to manually click on a timestamp greater than the one where it stopped, so it loads the song data, and then starting it over.

### Steps to Reproduce

1. Searched for an album.
2. Clicked on the album.
3. Started playing the album using the play button.
4. Song got stuck.
5. Hit play again.
6. Song restarted.
7. Check queue to see it changed.

### Anything else?

I think the album I was listening to does not have much to do with this issue, since i tried with another song and it happened again. Restarted Cider and my computer and it happened a few more times, and it has seemingly stopped happening (for now). Will try to keep updated and help as much as I can

**Comment by Hezkore** [comment]
I have a similar issue, where the play button acts very weird and some songs stops about a second or so into the song.
Sometimes the play button either doesn't do anything, or it plays the next song.

In the video below, the song "Frozen Light" stops after about a second.
And "Meeting the Master" never even starts, and clicking Play does nothing, until it eventually jumps to another song.

https://github.com/ciderapp/Cider-2/assets/1727541/2b10b1ad-9b7c-4b81-8c54-70061a4f02ad

**Comment by quiellll** [comment]
Yes!
I also forgot to add that. Sometimes, when it gets stuck, the play button gets its own life or something and toggles whenever i move the mouse, hover over anything, or click on another button (such as the queue one).

I've been using cider only for less than a week, but I had no problems on the previous release, before updating to the last version :(

**Comment by GGBond69** [comment]
have met the same issue too.after the song stopped,there is no react when clicking the play button.
And the playlist would be replaced by history songs:the order is inverted.

**Comment by stewartkyle** [comment]
I am having a very similar issue on Windows 11 using the latest build from the Microsoft Store (2.4.0_1). I open Cider, click to shuffle my library from the Songs page, and one of the following happens:

1. A song shows up as currently playing, but does not actually begin playing and is paused at 0:00. Pressing Play causes this song to be removed from currently playing and Cider then plays the most recent song from my history instead. My history is then used to populate the queue in reverse order.
2. Cider plays the first song normally. Eventually, when switching to the next song (sometimes it happens immediately on the second song, but sometimes it happens later in the queue), the song does not begin playing and the behaviour described in point 1 above happens.

Checking the console for errors, I have seen this error when the next song fails to start playing:

`GET <iTunes URL ending in .mp4> net::ERR_HTTP2_PROTOCOL_ERROR`

and these errors when Cider uses my history to populate the queue as described above:

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'inLibrary')`

`Uncaught (in promise) Error: The play() method was called without a previous stop() or pause() call.`

So, it seems like Cider is playing a song, encounters an error that prevents it from loading/playing the next song, and then generates an additional error when attempting to play() again because it was not actually told to stop playing the previous song.

I have tried clearing my Cider cache repeatedly as well as tweaking the settings with no luck.

This issue was not present on 2.3.x.

**Comment by johann2357** [comment]
This also is an issue for me, it stops randomly while playing a song. When I hit play again, the song restarts from the beginning. 

- Download source: `Itch`
- Operating system: `Arch Linux`
- Data obtained from `About` section of the app:
```json
{
  "version": "2.4.1",
  "commit": "d46a15d346cc8cc7ae5dfc5ddd19808e291e9bd7",
  "buildDate": "1717095597649",
  "framework": "electron",
  "isDev": "production",
  "platform": "linux",
  "platformFriendly": "Linux",
  "platformVersion": "6.9.7-arch1-1",
  "arch": "x64",
  "port": "9500",
  "steamdeck": false,
  "clientVersion": "9"
}
```

**Comment by braindotai** [comment]
It makes no sense to close this issues, this error has been with me from last year, I've been switching my distros and systems, but this issue loves me too much and follows me every system I go.
