### ISSUE TITLE
Updating the Cider app

### ISSUE THREAD

**Issue by DarthObi** [ciderapp/Cider-2#868]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### How did you download Cider?

Microsoft Store

### Operating System

Windows 

### Commit Hash

7b04e2c902aa2dab4065c276beb3302b22385240

### Build Timestamp

10/28/2024, 10:16:42 PM

### Describe the Bug

So I am trying to update cider, but it says I have an incompatible client. It suggests to go to the Microsoft Store and update there but I don't see anywhere that it shows to update the client. I am tired of constantly uninstalling and reinstalling for the latest version. Is there a way to fix this error?

### Steps to Reproduce

Opened Microsoft store,  under apps, it doesn't even show cider on there but I clicked "get updates". Then I go into library where I see cider, but there is not place to update the client.

**Comment by coredev-uk** [comment]
You do not need to uninstall and reinstall to update your client. When this message shows there will usually be one available, however when major releases occur Microsoft Store takes longer to process the release due to their checks and stuff, so 2.6.0 on MS store is not currently available, this has been posted on our social media and the release bulletin on Discord. 
If you cannot wait for a release, I suggest re-purchasing the app through donation or Itch.io so you can access taproom builds, which we control and directly update.
